name: generate-snake

on:
  schedule:
    - cron: "0 */12 * * *"   # every 12 hours
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - name: Generate crimson snake
        uses: Platane/snk@v3
        with:
          github_user_name: Prithvi8706
          outputs: |
            dist/github-snake.svg?color_snake=#e5e5ea&color_dots=#161618,#2e2e30,#5a5a5e,#98989d,#d1d1d6&dark_color_dots=#161618,#2e2e30,#5a5a5e,#98989d,#d1d1d6

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
